### ISSUE TITLE
renderStylesToString TypeError

### ISSUE THREAD

**Issue by alexseitsinger** [emotion-js/emotion#1116]
package.json

```
	"dependencies": {
		"@alexseitsinger/data-controller": "0.1.6",
		"@alexseitsinger/helpful-components": "0.1.21",
		"@alexseitsinger/react-ssr": "0.1.10",
		"@alexseitsinger/toggled-route": "0.1.0",
		"@babel/polyfill": "7.0.0",
		"@emotion/core": "10.0.5",
		"@emotion/styled": "10.0.5",
		"@fortawesome/fontawesome-svg-core": "1.2.0-14",
		"@fortawesome/free-brands-svg-icons": "5.1.0-11",
		"@fortawesome/free-solid-svg-icons": "5.1.0-11",
		"@fortawesome/react-fontawesome": "0.1.0-11",
		"@loadable/component": "5.2.2",
		"@loadable/server": "5.2.2",
		"axios": "0.19.0-beta.1",
		"axios-mock-adapter": "1.15.0",
		"connected-react-router": "6.0.0",
		"debounce": "1.2.0",
		"elapsed": "0.0.7",
		"emotion-server": "10.0.5",
		"fbemitter": "2.1.1",
		"history": "4.7.2",
		"js-cookie": "2.2.0",
		"prop-types": "15.6.0",
		"raven-for-redux": "1.3.1",
		"raven-js": "3.24.2",
		"react": "16.6.3",
		"react-dom": "16.6.3",
		"react-ga": "2.5.3",
		"react-helmet": "5.2.0",
		"react-hot-loader": "4.5.3",
		"react-redux": "6.0.0",
		"react-responsive": "4.1.0",
		"react-responsive-redux": "0.7.0",
		"react-router": "4.4.0-beta.6",
		"react-router-dom": "4.4.0-beta.6",
		"react-select": "2.1.2",
		"react-text-truncate": "0.13.1",
		"redux": "4.0.1",
		"redux-logger": "3.0.6",
		"redux-saga": "0.16.2",
		"redux-thunk": "2.2.0",
		"slugify": "1.2.9",
		"underscore": "1.8.3",
		"url-search-params-polyfill": "5.0.0"
	},
	"devDependencies": {
		"@babel/core": "7.2.0",
		"@babel/plugin-proposal-class-properties": "7.2.1",
		"@babel/plugin-syntax-dynamic-import": "7.2.0",
		"@babel/preset-env": "7.2.0",
		"@babel/preset-react": "7.0.0",
		"@loadable/babel-plugin": "5.0.1",
		"@loadable/webpack-plugin": "5.2.1",
		"babel-eslint": "8.0.2",
		"babel-jest": "23.6.0",
		"babel-loader": "8.0.4",
		"babel-plugin-css-modules-transform": "1.6.2",
		"babel-plugin-dynamic-import-node": "2.2.0",
		"babel-plugin-emotion": "10.0.5",
		"babel-plugin-transform-react-remove-prop-types": "0.4.21",
		"css-loader": "0.28.7",
		"dotenv-webpack": "1.5.7",
		"eslint": "4.12.1",
		"eslint-plugin-babel": "4.1.2",
		"eslint-plugin-react": "7.5.1",
		"file-loader": "1.1.5",
		"jest": "23.6.0",
		"jest-emotion": "9.2.11",
		"mini-css-extract-plugin": "0.4.0",
		"nodemon": "1.17.4",
		"style-loader": "0.20.3",
		"uglifyjs-webpack-plugin": "1.1.8",
		"url-loader": "0.6.2",
		"webpack": "4.27.1",
		"webpack-bundle-tracker": "0.2.0",
		"webpack-cli": "2.0.14",
		"webpack-dev-server": "3.1.8",
		"webpack-merge": "4.1.1",
		"webpack-node-externals": "1.7.2",
		"webpack-s3-plugin": "1.0.0-rc.0"
	},
```

**Reproduction:**

[https://www.github.com/alexseitsinger/simple-modal-example](https://www.github.com/alexseitsinger/simple-modal-example)

**Problem description:**

Using { renderStylesToString } in `frontend/src/render.js` results in:
```
/usr/home/main/mnt/da0/code/projects/library/simple-modal-example/sites/main/node_modules/create-emotion-server/dist/create-emotion-server.cjs.dev.js:155                                                                
if (cache.compat !== true) {                                                                           
               ^                                                                                                                                                                                   
TypeError: Cannot read property 'compat' of undefined                                                    
    at index (/usr/home/main/mnt/da0/code/projects/library/simple-modal-example/sites/main/node_modules/create-emotion-server/dist/create-emotion-server.cjs.dev.js:155:13)
    at Object.<anonymous> (/usr/home/main/mnt/da0/code/projects/library/simple-modal-example/sites/main/node_modules/emotion-server/dist/emotion-server.cjs.dev.js:10:28)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal.modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:19)
    at Object.<anonymous> (/usr/home/main/mnt/da0/code/projects/library/simple-modal-example/sites/main/node_modules/emotion-server/dist/emotion-server.cjs.js:6:20)
```

**Suggested solution:**

I noticed in the src/ that this error is thrown by is commented as a feature for the new API. Perhaps something didn't get changed property when updating to the latest version?

**Comment by alexseitsinger** [comment]
I believe this issue was the result of missing "emotion": 10.0.5. I had removed it once I migrated to the /@emotion/core and /@emotion/styled packages.
