### ISSUE TITLE
Module build babel-loader fails when running start:site (creating a local version of the repo)

### ISSUE THREAD

**Issue by desmap** [emotion-js/emotion#1120]
- `emotion` version: 10.0.0
- `react` version: 16.5.2
- `node` version: 10.13.0
- `ubuntu` version: 16.04
- `yarn` version: 1.12.3

**What you did:**

`yarn start:site`

**What happened:**

```
here ./.cache/develop-static-entry.js
Module build failed (from ../node_modules/gatsby/dist/utils/babel-loader.js):
Error: Cannot find module '@emotion/babel-preset-css-prop'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at require.resolve (/home/d/emotion/node_modules/v8-compile-cache/v8-compile-cache.js:162:23)
    at pluginBabelConfig.stages.(anonymous function).presets.forEach.preset (/home/d/emotion/node_modules/gatsby/dist/utils/babel-loader-helpers.js:65:47)
    at Array.forEach (<anonymous>)
    at prepareOptions (/home/d/emotion/node_modules/gatsby/dist/utils/babel-loader-helpers.js:64:43)
    at Object.config (/home/d/emotion/node_modules/gatsby/dist/utils/babel-loader.js:42:31)
    at Object.<anonymous> (/home/d/emotion/node_modules/babel-loader/lib/index.js:88:42)
    at Generator.next (<anonymous>)
    at step (/home/d/emotion/node_modules/babel-loader/lib/index.js:3:221)
    at _next (/home/d/emotion/node_modules/babel-loader/lib/index.js:3:409)
    at tryCatcher (/home/d/emotion/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/d/emotion/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/d/emotion/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/d/emotion/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/home/d/emotion/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/d/emotion/node_modules/bluebird/js/release/async.js:131:9)
error There was an error compiling the html.js component for the development server.
```

**Reproduction:**

`yarn start:site`

**Problem description:**

Local version doesn't build/run out of the box. Btw, had also to `yarn global add lerna preconstruct jest` before. Shouldn't they get installed locally by yarn/npm install instead of assuming that they are already installed?

**Suggested solution:**

Local version should work out-of-box without any prerequirements after a git clone.

**Comment by Andarist** [comment]
This had to be a temporary issue - I've just tried this after doing a fresh clone and everything works as expected.
