### ISSUE TITLE
Jest snapshots fail using jest-emotion when classes use composition

### ISSUE THREAD

**Issue by meebix** [emotion-js/emotion#1218]
When using Jest snapshots with an Emotion class that contains composition, the jest snapshot fails. I am using jest-emotion, but it still fails.

My `.tsx` file containing the Emotion classes looks like this:

```js
const Option = styled.div`
  ${p => p.theme.mq(p.theme.option)};
`;

const Options = styled.div`
  ${Option}:first-child {
    border-top: none;
  }
`;
```

**I can confirm that if I remove `Options` class and the corresponding JSX, the snapshot tests work fine. So this is the problem, the composition.**

My jest config contains:

```js
{
  ...
  snapshotSerializers: ['jest-emotion']
}
```

The error:

```js
  ● <OptionList /> › should render with all available passed in options

    Component selectors can only be used in conjunction with babel-plugin-emotion.

      33 |   it('should render with all available passed in options', () => {
      34 |     const tree = renderer
    > 35 |       .create(
         |        ^
      36 |         <OptionList
      37 |           tableTitle="Arguments"
      38 |           styles={{ title: { color: 'green' } }}

      at handleInterpolation (node_modules/@emotion/serialize/dist/serialize.cjs.dev.js:85:13)
      at Object.serializeStyles (node_modules/@emotion/serialize/dist/serialize.cjs.dev.js:232:15)
      at node_modules/@emotion/styled-base/dist/styled-base.cjs.dev.js:99:36
      at updateContextConsumer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7402:19)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7568:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10358:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10390:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10476:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11342:7)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11254:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11228:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11097:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10907:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11494:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11522:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11533:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12079:5)
      at Object.<anonymous> (src/OptionList/__tests__/OptionsList.test.tsx:35:8)
```

My versions:

```js
"jest": "23.6.0"
"jest-emotion": "^10.0.7"
"ts-jest": "23.10.5"
"babel-plugin-emotion": "10.0.6"
"@emotion/core": "^10.0.6"
"@emotion/styled": "^10.0.6"
```

**Comment by gleb-rudenko** [comment]
Facing the same issue, is it a bug? or there might be some workaround.

**Comment by Andarist** [comment]
The thrown error gives a good hint about what is wrong - most likely you didn't set up babel correctly to make interpolating styled components (as classNames) possible. If you provide a repro case I will gladly take a look and give you advice on how you should fix this - but until then I'm going to close this issue to keep the issue tracker clean.
