### ISSUE TITLE
issue when using @emotion/styled with babel programmatic

### ISSUE THREAD

**Issue by GiladShoham** [emotion-js/emotion#1439]
**Current behavior:**

Building the same code using babel cli is working but using babel programmatic API is breaking.

Error:
```
/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:341
  var finalPath = filename === rootPath ? 'root' : filename.slice(rootPath.length);
                                                            ^

TypeError: Cannot read property 'slice' of undefined
    at getTargetClassName (/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:341:61)
    at getStyledOptions (/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:515:78)
    at /private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:685:54
    at Array.forEach (<anonymous>)
    at /private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:643:26
    at Object.macroWrapper [as @emotion/styled] (/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/babel-plugin-macros/dist/index.js:61:12)
    at PluginPass.ImportDeclaration (/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:891:45)
    at newFn (/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/private/tmp/bit-emotion-reproduce/babel-programmatic/node_modules/@babel/traverse/lib/path/context.js:40:17)
```

**To reproduce:**

A full example with steps to reproduce both with CLI and programmatic is available here:
https://github.com/GiladShoham/bit-emotion-reproduce

**Expected behavior:**

The app should be built with babel programmatic API as well.

**Environment information:**

- `react` version: ^16.8.6
- `emotion` version: ^10.0.14

**Comment by Andarist** [comment]
Thank you for the report and repro case! I've prepared a fix in https://github.com/emotion-js/emotion/pull/1574
