### ISSUE TITLE
Enzyme Detects Twice the nodes as EmotionCssPropInternal gets injected into tree

### ISSUE THREAD

**Issue by azizhk** [emotion-js/emotion#1686]
**Current behavior:**
I'm upgrading emotion from v9 to v10 and am getting this error:

```
Method “simulate” is meant to be run on 1 node. 2 found instead.

      142 |     );
      143 | 
    > 144 |     component.find(`#${WRAPPER_ID}`).simulate("click");
          |                                           ^
      at ReactWrapper.single (../../node_modules/enzyme/src/ReactWrapper.js:1166:13)
      at ReactWrapper.simulate (../../node_modules/enzyme/src/ReactWrapper.js:665:17)
      at Object.test (src/components/__tests__/phonenumberinput.test.tsx:144:43)
```

**To reproduce:**
Sample test case with jest, enzyme
```jsx
import * as React from "react";
import { mount } from "enzyme";

const WRAPPER_ID = "wrapper-test-id";

function getComponent() {
  return (
    <div id={WRAPPER_ID} css={{ backgroud: "green" }}>
      <span>Hello</span>
    </div>
  );
}

describe("Component: Select", () => {
  test("should open when input is clicked", () => {
    const component = mount(getComponent());
    component.find(`#${WRAPPER_ID}`).simulate("click");

    expect(component.find(`#${WRAPPER_ID}`)).toHaveLength(1);
  });
});
```

**Expected behavior:**
Only one element getting selected. Maybe `EmotionCssPropInternal` should not get injected into the tree.

**Environment information:**

- `react` version "16.12.0"
- `emotion` version "10.0.23"
- `@emotion/core` version "10.0.22"
- `@emotion/css` version "10.0.22"
- `jest-emotion` version "10.0.25"
- `@emotion/babel-preset-css-prop` version "10.0.23"
- `jest` version "24.9.0"
- `enzyme` version "3.10.0"

I know based on [Testing Library Query Practices](https://testing-library.com/docs/guide-which-query#priority) we should not be selecting elements based on ids, classnames or test-ids, and are in process of migrating. But that would be a big task for our big suite of components: https://github.com/anarock/pebble/pull/292/files

**Comment by azizhk** [comment]
Found the solution here: https://github.com/airbnb/enzyme/issues/836
Need to use `.hostNodes()` to filter it down to the HTML elements.

So sorry for creating this issue.
Thanks for awesome work behind emotion.
