### ISSUE TITLE
Jest tests with both emotion & styled-components 

### ISSUE THREAD

**Issue by ericclemmons** [emotion-js/emotion#248]
- `emotion` version: 7.0.12
- `react` version: 15.4.1

Relevant code.

```javascript
// .babelrc
plugins: {  "emotion/babel" }
```

What you did:

- Ran my Jest unit tests (which generate snapshots via stories)

What happened:
> FAIL  src/components/SchoolBanners/SchoolBanners.stories.js
>  ● School Banners › Base Example
>
> Invariant Violation: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

<details><summary>More</summary>
      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:195:114)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactTestComponent.mountChildren (node_modules/react-test-renderer/lib/ReactMultiChild.js:238:44)
      at ReactTestComponent.mountComponent (node_modules/react-test-renderer/lib/ReactTestRenderer.js:62:10)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper._updateRenderedComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:765:40)
      at ReactCompositeComponentWrapper._performComponentUpdate (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:724:10)
      at ReactCompositeComponentWrapper.updateComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:645:12)
      at ReactCompositeComponentWrapper.performUpdateIfNecessary (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:561:12)
      at Object.performUpdateIfNecessary (node_modules/react-test-renderer/lib/ReactReconciler.js:157:22)
      at runBatchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:150:21)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-test-renderer/lib/ReactUpdates.js:89:32)
      at Object.flushBatchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:172:19)
      at ReactDefaultBatchingStrategyTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.<anonymous> (src/__mocks__/storybook.js:11:40)
      at process._tickCallback (internal/process/next_tick.js:103:7)
</details>

Reproduction:

- N/A

Problem description:

- What's important to note is that **this test is using `styled-components` within it** and failing with this error, while the other tests using `emotion` are working fine.

Suggested solution:

- Remove `emotion/babel` when `process.env.NODE_ENV === "test"`, **but** this causes expressions like `styled.button` to throw errors like:

  > TypeError: _react2.default.button is not a function

  Assuming because `emotion/babel` translates this to `styled("button")`.

**Comment by thangngoc89** [comment]
This is because babel plugin transpiles emotion/styled-components like template literals so it breaks styled-component. And emotion can't work without the babel plugin.

**Comment by tkh44** [comment]
It can work without the plugin but it's really only good for object styles. We might be able to support checking if the emotion import is at the top of a file before transforming it. I'm not absolutely sure this is more of @mitchellhamilton's area.

**Comment by mitchellhamilton** [comment]
We could do a check for that but I'm not sure if it's a good idea because it would mean that people couldn't use custom runtimes (e.g. emotion-vue).

I think there are two possible solutions to this problem. Firstly, use [the babel macro](https://github.com/tkh44/emotion/blob/master/docs/babel-macros.md), this would fix the problem but it would mean you can't use `extractStatic`. Secondly, run rename styled-components' styled so emotion's babel plugin doesn't change them. I wrote [a little codemod](http://astexplorer.net/#/gist/49ee57485fdf815dea00098437a2a0a1/5236b6ebabe00f2b59516d9bc49100b0abee078c) to do this, it's not perfect but it should work in most cases.

**Comment by ericclemmons** [comment]
I've done babel plugins myself (was adding HMR to functional components) and keying off of `emotion`'s variable assignment of `styled` would be the most predictable path, as that would solidify `emotion/babel`'s behavior.
