### ISSUE TITLE
Using jest, mui, nextjs: TypeError: React.createContext is not a function that traces to emotion

### ISSUE THREAD

**Issue by ehguo** [emotion-js/emotion#2613]
**Current behavior:**

Getting a TypeError: React.createContext is not a function with a pretty barebones unit test. I've included a sample repo in the reproduce section below.

```js
TypeError: React.createContext is not a function

       6 | interface PropTypes {
       7 |   userName?: string;
    >  8 |   userImage?: string;
         |               ^
       9 | }
      10 |
      11 | const AppBar = styled(MuiAppBar)`

      at Object.<anonymous> (node_modules/@emotion/react/dist/emotion-element-c24e4fdd.cjs.dev.js:20:48)
      at Object.<anonymous> (node_modules/@emotion/react/dist/emotion-react.cjs.dev.js:7:22)
      at Object.<anonymous> (node_modules/@emotion/react/dist/emotion-react.cjs.js:6:20)
      at Object.<anonymous> (node_modules/@emotion/styled/dist/emotion-styled.cjs.dev.js:6:1)
      at Object.<anonymous> (node_modules/@emotion/styled/dist/emotion-styled.cjs.js:6:20)
      at Object.<anonymous> (node_modules/@mui/styled-engine/node/index.js:45:38)
      at Object.<anonymous> (node_modules/@mui/system/index.js:296:21)
      at Object.<anonymous> (node_modules/@mui/material/node/styles/adaptV4Theme.js:14:15)
      at Object.<anonymous> (node_modules/@mui/material/node/styles/index.js:207:44)
      at Object.<anonymous> (components/Header.tsx:8:15)
      at Object.<anonymous> (components/Header.spec.tsx:4:38)
      at async TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (node_modules/@jest/core/build/runJest.js:404:19)
```

**To reproduce:**

Found it to be reproducible with a brand new repo with basically nothing in it:
https://github.com/ehguo/emotion-bug

1. clone
2. npm install
3. npm run test

**Expected behavior:**
Test should run without error

**Environment information:**
```js
  "dependencies": {
    "@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.7.1",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.2.5",
    "@mui/material": "^5.2.7",
    "next": "12.0.7",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "ts-node": "^10.4.0"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@types/node": "17.0.8",
    "@types/react": "17.0.38",
    "eslint": "8.6.0",
    "eslint-config-next": "12.0.7",
    "jest": "^27.4.6",
    "typescript": "4.5.4"
  }
```

**Comment by Andarist** [comment]
I'm not completely sure what is exactly going on but I've investigated this and this is definitely not an issue with Emotion.

When running Jest the `require('react')` within `@emotion/react` returns an empty object - note that doing the same with a bare node in the same directory loads the content of the actual React package as expected. The problem goes away if we apply this patch to the given repro case:
```diff
diff --git a/jest.config.ts b/jest.config.ts
index 8070ec4..2008727 100644
--- a/jest.config.ts
+++ b/jest.config.ts
@@ -10,7 +10,7 @@ const createJestConfig = nextJest({
 const customJestConfig = {
   setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
   // if using TypeScript with a baseUrl set to the root directory then you need the below for alias' to work
-  moduleDirectories: ['node_modules', '.'],
+  moduleDirectories: ['node_modules'],
   testEnvironment: 'jest-environment-jsdom',
 };
 ```

Note that this ends up with a different error - but it's related to the JSDOM and the tested component so I assume that the reported issue gets resolved with this patch and you need to check out that other problem separately.

**Comment by AndrewRPorter** [comment]
@ehguo did you find a way around this? Currently experiencing this issue with jest as well.

**Comment by ehguo** [comment]
> @ehguo did you find a way around this? Currently experiencing this issue with jest as well.

I did, I believe the solution for me was making the moduleDirectories line:
```js
  moduleDirectories: ['node_modules', '<rootDir>', 'src'],
```

there were a few other changes in the same PR that fixed the issue though so let me know if that doesn't work.
