### ISSUE TITLE
StyleSheet._insertTag: Node before which new node is to be inserted is not a child of this node

### ISSUE THREAD

**Issue by crates** [emotion-js/emotion#2919]
**Current behavior:**

We're getting a strange bug happening only when running Cypress in Electron mode. The error is coming from Emotion, but I'm unsure if it's specific to Cypress, Emotion, MUI or React Admin.

The error, and stack trace, look like this:

```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at StyleSheet._insertTag (http://localhost:4200/vendor.js:15183:23)
    at StyleSheet.insert (http://localhost:4200/vendor.js:15211:12)
    at Array.finalizingPlugins (http://localhost:4200/vendor.js:13827:24)
    at http://localhost:4200/vendor.js:333250:27
    at serialize (http://localhost:4200/vendor.js:333712:13)
    at Array.prefixer (http://localhost:4200/vendor.js:333281:70)
    at http://localhost:4200/vendor.js:333250:27
    at serialize (http://localhost:4200/vendor.js:333712:13)
    at stylis (http://localhost:4200/vendor.js:13838:63)
    at Object.insert (http://localhost:4200/vendor.js:13852:7)
```

**To reproduce:**

Unfortunately I haven't the slightest clue on how to reproduce this in an easy way for your team to digest. Sincere apologies.

**Expected behavior:**

I suppose I'd expect the code in your `_insertTag` method to check whether an insert operation is a valid one before attempting it.

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.10.4

**Comment by Andarist** [comment]
My first thought is that something is tampering with your DOM. Are you able to reproduce this reliably?

**Comment by hcharley** [comment]
I'm also seeing this (in Cypress only--I'm using electron fwiw). I would like to come later and add additional details, but just wanting to note that you're not alone @crates.

**Comment by LBBO** [comment]
I'm also encountering a similar issue while working on Signal Desktop (an Electron app). My error message is slightly different:

```
TypeError: Cannot read properties of null (reading 'insertBefore')
    at StyleSheet2._insertTag (/path/to/Signal-Desktop/preload.bundle.js:244267:27)
    at StyleSheet2.insert (/path/to/Signal-Desktop/preload.bundle.js:244287:16)
    at /path/to/Signal-Desktop/preload.bundle.js:245334:24
    at Array.<anonymous> (/path/to/Signal-Desktop/preload.bundle.js:244877:15)
    at /path/to/Signal-Desktop/preload.bundle.js:244868:25
    at Object.te [as serialize] (/path/to/Signal-Desktop/preload.bundle.js:244844:17)
    at stylis$1 (/path/to/Signal-Desktop/preload.bundle.js:245338:25)
    at Object.insert (/path/to/Signal-Desktop/preload.bundle.js:245342:11)
    at Object.insertStyles (/path/to/Signal-Desktop/preload.bundle.js:246357:35)
    at /path/to/Signal-Desktop/preload.bundle.js:246768:23
```

A similar error should be reproducible by running [my feature branch](https://github.com/LBBO/Signal-Desktop/tree/ab5ff666f9a7ef24aa3cc95e7914ab65f89cf153) (links to specific commit for future readers) locally (the above error message is after a couple of code changes in some locally linked repositories, but IIRC the error was very similar before those changes).

Ultimately, the issue was caused in the import of another dependency (@giphy/react-components's Grid component) which creates a styled div at the top level (i.e. at import, something like `const GifContainer = styled.div...`). Ultimately, this leads to StyleSheet.container being initialized with `null` and since it's cached, that issue is never fixed. I was able to circumvent this issue by wrapping the component in a `Suspense` that defers its import:

```tsx
const Grid = React.lazy(async () => ({
  default: (await import('@giphy/react-components')).Grid,
}))

const MyComponent: React.FC = () => {
  // ...
  return <Suspense fallback={fallback}>
    <Grid />
  </Suspense>
}
```

Since I'm not that well-versed in Electron, I'm not sure if there's a better way to handle this sort of stuff. Probably it's possible to somehow ensure the dependency isn't imported before the web view (or whatever it is, sorry for potentially imprecise terminology here) or so. Most likely emotion is behaving as intended here, but maybe some documentation could be added? Or perhaps an option to periodically refresh the container if the default is being used or something? I'm happy to create a PR for this once the desired changes have been identified.

Just in case someone's curious: this is where the StyleSheet is initialized; the initialization of `container` is a bit higher at line 98: https://github.com/emotion-js/emotion/blob/92be52d894c7d81d013285e9dfe90820e6b178f8/packages/cache/src/index.js#L250

**Comment by Andarist** [comment]
Hm, it's quite interesting because `document.head` should always be available - even though `document.body` gets only available after parsing opening `<body>`. You can take a look at this simple codesandbox that demonstrates this:
https://03605g.csb.app/

So my question would be - why Electron is different? How does it execute scripts **before** even parsing HTML and creating relevant document properties etc.

**Comment by BtheGit** [comment]
I'm having a similar issue right now working on a chrome extension. Any library that I try to use that has emotion as a dependency fails. My content script runs at document_start and it would seem that emotion just won't play nice with that. I'm having to back out any library with emotion right now since I don't know how to tell emotion to wait for the dom (even though I'm only using it in components that are waiting for DOMContentLoaded before rendering.

```
Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at StyleSheet._insertTag (content-main.8909edb2.js:70186:29)
    at StyleSheet.insert (content-main.8909edb2.js:70207:64)
    at Array.finalizingPlugins (content-main.8909edb2.js:70091:53)
    at content-main.8909edb2.js:70795:44
    at fe (content-main.8909edb2.js:70774:36)
    at stylis (content-main.8909edb2.js:70100:38)
    at Object.insert (content-main.8909edb2.js:70109:9)
    at insertStyles (content-main.8909edb2.js:71387:37)
    at content-main.8909edb2.js:71059:40
    at commitHookEffectListMount (content-main.8909edb2.js:46501:38)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47202:25)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47197:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47197:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47226:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47197:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47197:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47233:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47233:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47197:17)
    at recursivelyTraverseMutationEffects (content-main.8909edb2.js:47181:17)
    at commitMutationEffectsOnFiber (content-main.8909edb2.js:47289:17)
    at commitMutationEffects (content-main.8909edb2.js:47159:9)
    at commitRootImpl (content-main.8909edb2.js:48938:13)
    at commitRoot (content-main.8909edb2.js:48853:13)
    at finishConcurrentRender (content-main.8909edb2.js:48361:17)
    at performConcurrentWorkOnRoot (content-main.8909edb2.js:48247:17)
    at workLoop (content-main.8909edb2.js:51040:44)
    at flushWork (content-main.8909edb2.js:51022:20)
    at MessagePort.performWorkUntilDeadline (content-main.8909edb2.js:51226:31)
StyleSheet._insertTag @ content-main.8909edb2.js:70186
insert @ content-main.8909edb2.js:70207
finalizingPlugins @ content-main.8909edb2.js:70091
(anonymous) @ content-main.8909edb2.js:70795
fe @ content-main.8909edb2.js:70774
stylis @ content-main.8909edb2.js:70100
insert @ content-main.8909edb2.js:70109
insertStyles @ content-main.8909edb2.js:71387
(anonymous) @ content-main.8909edb2.js:71059
commitHookEffectListMount @ content-main.8909edb2.js:46501
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47202
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47197
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47197
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47226
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47197
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47197
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47233
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47233
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47197
recursivelyTraverseMutationEffects @ content-main.8909edb2.js:47181
commitMutationEffectsOnFiber @ content-main.8909edb2.js:47289
commitMutationEffects @ content-main.8909edb2.js:47159
commitRootImpl @ content-main.8909edb2.js:48938
commitRoot @ content-main.8909edb2.js:48853
finishConcurrentRender @ content-main.8909edb2.js:48361
performConcurrentWorkOnRoot @ content-main.8909edb2.js:48247
workLoop @ content-main.8909edb2.js:51040
flushWork @ content-main.8909edb2.js:51022
performWorkUntilDeadline @ content-main.8909edb2.js:51226
```

**Comment by Andarist** [comment]
@BtheGit can u share a repro case?

**Comment by BtheGit** [comment]
@Andarist I'm happy to try. Though not sure what form that would take. The project I'm working on is a chrome extension that augments the Geoguessr website and requires me to load a content script at document_start in order to inject code into the main execution world of the page before any dependencies load. After that, the content script waits for DOMContentLoad and then starts to render components for UI.

However, every library I've tried with emotion as a dependency (react-select, mui-x-data-grid, etc.) fails immediately on importing the dependency into a component, with the above issue. I guess emotion doesn't have any expectation that it's going to need to wait for DOM elements before it starts adding scripts to what I assume is the head? (Neither the head nor the body exist at the time of the content script being executed, only document.documentElement does).

**Comment by BtheGit** [comment]
@Andarist I made you a demo project that reproduces the issue for me. Hope that makes it clearer!

https://github.com/BtheGit/repro-emotion-bug

**Comment by xydian** [comment]
same issue for me, also using MUI. Happening in chrome environment so not specific to electron. 

For me the issue is happening when rendering a MUI Select component. Once a select component appears on the page the issue occurs. When I remove the select component everything works fine. 

```
react-dom.development.js:22839 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at StyleSheet._insertTag (http://localhost:3000/static/js/bundle.js:64768:23)
    at StyleSheet.insert (http://localhost:3000/static/js/bundle.js:64791:12)
    at Array.finalizingPlugins (http://localhost:3000/static/js/bundle.js:63631:24)
    at http://localhost:3000/static/js/bundle.js:357156:61
    at serialize (http://localhost:3000/static/js/bundle.js:357693:46)
    at Array.prefixer (http://localhost:3000/static/js/bundle.js:63539:63)
    at http://localhost:3000/static/js/bundle.js:357156:61
    at serialize (http://localhost:3000/static/js/bundle.js:357693:46)
    at stylis (http://localhost:3000/static/js/bundle.js:63641:63)
    at Object.insert (http://localhost:3000/static/js/bundle.js:63652:7)
```

```
react-dom.development.js:18687 The above error occurred in the <EmotionGlobal> component:

    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at GlobalStyles (http://localhost:3000/static/js/bundle.js:106228:5)
    at GlobalStyles
    at InputBase (http://localhost:3000/static/js/bundle.js:91407:83)
    at OutlinedInput (http://localhost:3000/static/js/bundle.js:95864:82)
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Select (http://localhost:3000/static/js/bundle.js:97068:82)
    at div
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Box (http://localhost:3000/static/js/bundle.js:107547:72)
    at MuiBoxComponent
    at div
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Box (http://localhost:3000/static/js/bundle.js:107547:72)
    at MuiBoxComponent
    at div
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Paper (http://localhost:3000/static/js/bundle.js:96203:82)
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Transition (http://localhost:3000/static/js/bundle.js:250456:30)
    at Slide (http://localhost:3000/static/js/bundle.js:98115:77)
    at div
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Drawer (http://localhost:3000/static/js/bundle.js:87540:83)
    at Drawer (http://localhost:3000/static/js/bundle.js:53019:5)
    at div
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Box (http://localhost:3000/static/js/bundle.js:107547:72)
    at MuiBoxComponent
    at Layout (http://localhost:3000/static/js/bundle.js:53422:5)
    at DrawerResult (http://localhost:3000/static/js/bundle.js:21608:67)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:249671:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:250008:26)
    at AddingSlabsStoreProvider (http://localhost:3000/static/js/bundle.js:37758:5)
    at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
    at ElementLoadStoreProvider (http://localhost:3000/static/js/bundle.js:38044:5)
    at StructuralPlanningStoreProvider (http://localhost:3000/static/js/bundle.js:39065:5)
    at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
    at ElementSelectionStoreProvider (http://localhost:3000/static/js/bundle.js:38166:5)
    at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
    at ControlStoreProvider (http://localhost:3000/static/js/bundle.js:37928:5)
    at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
    at SystemManagerStoreProvider (http://localhost:3000/static/js/bundle.js:39278:5)
    at ModelStoreProvider (http://localhost:3000/static/js/bundle.js:38667:5)
    at Editor (http://localhost:3000/static/js/bundle.js:12679:66)
    at ProtectedRoute (http://localhost:3000/static/js/bundle.js:1973:14)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:249671:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:250008:26)
    at main
    at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
    at Box (http://localhost:3000/static/js/bundle.js:107547:72)
    at MuiBoxComponent
    at Layout (http://localhost:3000/static/js/bundle.js:53327:5)
    at ProtectedRoute (http://localhost:3000/static/js/bundle.js:1973:14)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:249671:5)
    at Routes (http://localhost:3000/static/js/bundle.js:250093:5)
    at App (http://localhost:3000/static/js/bundle.js:1732:55)
    at Auth0Provider (http://localhost:3000/static/js/bundle.js:62771:23)
    at AuthenticationProvider (http://localhost:3000/static/js/bundle.js:2129:5)
    at LocationProvider (http://localhost:3000/static/js/bundle.js:282185:20)
    at RouteAdapter (http://localhost:3000/static/js/bundle.js:52777:5)
    at QueryParamProvider (http://localhost:3000/static/js/bundle.js:282335:21)
    at Router (http://localhost:3000/static/js/bundle.js:250031:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:248363:5)
    at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:106824:70)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:106099:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:106843:5)
    at SnackbarProvider (http://localhost:3000/static/js/bundle.js:187279:24)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:227001:21)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:128856:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by KevichVinc** [comment]
Hi everyone,

Faced same problem using mui, react 18.2 and craft.js after page refresh and navigating between pages using react-router-dom.

Solution which helped me was adding conditional rendering to pages:

`cosnt [isVisible, setIsVisible] = useState(false)

 useEffect(()=>{
   setIsVisible(true)
   
   return () => { setIsVisible(false)}
 },[])
`

I still think its not quite right to do so, but at least app is working now

Would be great if someone could explain this in details, but my thought is that emotion tries to set styles before tah header is avaliable, but im not sure

**Comment by realamirhe** [comment]
> [!CAUTION]
> The same error happen in the [google web cache](webcache.googleusercontent.com), the site restructure layout, and extract section of head into its own head, so `insertionPoint` might not exist in the head. Because `before` doesn't exist inside the head anymore



https://github.com/emotion-js/emotion/blob/b0014b4edc6be047e0a94d8c627d4e52ecccd371/packages/sheet/src/index.js#L105

**Comment by KevichVinc** [comment]
Found the problem - i've been interacting with <head> tag, so it seems because i changed its content (i added base tag for routing on sub-dirs), it crashed the flow of style tags

So my advise would be check if you or some of libs are interactiong with <head> tag, it could be the case

**Comment by alexandredepape** [comment]
Same thing for my on code inside a chrome extension content script injected at document_start, when switching to document_idle, it works against, but I'd like to inject the script at document_start..

> same issue for me, also using MUI. Happening in chrome environment so not specific to electron.
> 
> For me the issue is happening when rendering a MUI Select component. Once a select component appears on the page the issue occurs. When I remove the select component everything works fine.
> 
> ```
> react-dom.development.js:22839 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
>     at StyleSheet._insertTag (http://localhost:3000/static/js/bundle.js:64768:23)
>     at StyleSheet.insert (http://localhost:3000/static/js/bundle.js:64791:12)
>     at Array.finalizingPlugins (http://localhost:3000/static/js/bundle.js:63631:24)
>     at http://localhost:3000/static/js/bundle.js:357156:61
>     at serialize (http://localhost:3000/static/js/bundle.js:357693:46)
>     at Array.prefixer (http://localhost:3000/static/js/bundle.js:63539:63)
>     at http://localhost:3000/static/js/bundle.js:357156:61
>     at serialize (http://localhost:3000/static/js/bundle.js:357693:46)
>     at stylis (http://localhost:3000/static/js/bundle.js:63641:63)
>     at Object.insert (http://localhost:3000/static/js/bundle.js:63652:7)
> ```
> 
> ```
> react-dom.development.js:18687 The above error occurred in the <EmotionGlobal> component:
> 
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at GlobalStyles (http://localhost:3000/static/js/bundle.js:106228:5)
>     at GlobalStyles
>     at InputBase (http://localhost:3000/static/js/bundle.js:91407:83)
>     at OutlinedInput (http://localhost:3000/static/js/bundle.js:95864:82)
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Select (http://localhost:3000/static/js/bundle.js:97068:82)
>     at div
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Box (http://localhost:3000/static/js/bundle.js:107547:72)
>     at MuiBoxComponent
>     at div
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Box (http://localhost:3000/static/js/bundle.js:107547:72)
>     at MuiBoxComponent
>     at div
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Paper (http://localhost:3000/static/js/bundle.js:96203:82)
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Transition (http://localhost:3000/static/js/bundle.js:250456:30)
>     at Slide (http://localhost:3000/static/js/bundle.js:98115:77)
>     at div
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Drawer (http://localhost:3000/static/js/bundle.js:87540:83)
>     at Drawer (http://localhost:3000/static/js/bundle.js:53019:5)
>     at div
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Box (http://localhost:3000/static/js/bundle.js:107547:72)
>     at MuiBoxComponent
>     at Layout (http://localhost:3000/static/js/bundle.js:53422:5)
>     at DrawerResult (http://localhost:3000/static/js/bundle.js:21608:67)
>     at RenderedRoute (http://localhost:3000/static/js/bundle.js:249671:5)
>     at Outlet (http://localhost:3000/static/js/bundle.js:250008:26)
>     at AddingSlabsStoreProvider (http://localhost:3000/static/js/bundle.js:37758:5)
>     at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
>     at ElementLoadStoreProvider (http://localhost:3000/static/js/bundle.js:38044:5)
>     at StructuralPlanningStoreProvider (http://localhost:3000/static/js/bundle.js:39065:5)
>     at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
>     at ElementSelectionStoreProvider (http://localhost:3000/static/js/bundle.js:38166:5)
>     at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
>     at ControlStoreProvider (http://localhost:3000/static/js/bundle.js:37928:5)
>     at Provider (http://localhost:3000/static/js/bundle.js:288261:7)
>     at SystemManagerStoreProvider (http://localhost:3000/static/js/bundle.js:39278:5)
>     at ModelStoreProvider (http://localhost:3000/static/js/bundle.js:38667:5)
>     at Editor (http://localhost:3000/static/js/bundle.js:12679:66)
>     at ProtectedRoute (http://localhost:3000/static/js/bundle.js:1973:14)
>     at RenderedRoute (http://localhost:3000/static/js/bundle.js:249671:5)
>     at Outlet (http://localhost:3000/static/js/bundle.js:250008:26)
>     at main
>     at captureCommitPhaseError (http://localhost:3000/static/js/bundle.js:216603:29)
>     at Box (http://localhost:3000/static/js/bundle.js:107547:72)
>     at MuiBoxComponent
>     at Layout (http://localhost:3000/static/js/bundle.js:53327:5)
>     at ProtectedRoute (http://localhost:3000/static/js/bundle.js:1973:14)
>     at RenderedRoute (http://localhost:3000/static/js/bundle.js:249671:5)
>     at Routes (http://localhost:3000/static/js/bundle.js:250093:5)
>     at App (http://localhost:3000/static/js/bundle.js:1732:55)
>     at Auth0Provider (http://localhost:3000/static/js/bundle.js:62771:23)
>     at AuthenticationProvider (http://localhost:3000/static/js/bundle.js:2129:5)
>     at LocationProvider (http://localhost:3000/static/js/bundle.js:282185:20)
>     at RouteAdapter (http://localhost:3000/static/js/bundle.js:52777:5)
>     at QueryParamProvider (http://localhost:3000/static/js/bundle.js:282335:21)
>     at Router (http://localhost:3000/static/js/bundle.js:250031:15)
>     at BrowserRouter (http://localhost:3000/static/js/bundle.js:248363:5)
>     at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:106824:70)
>     at ThemeProvider (http://localhost:3000/static/js/bundle.js:106099:5)
>     at ThemeProvider (http://localhost:3000/static/js/bundle.js:106843:5)
>     at SnackbarProvider (http://localhost:3000/static/js/bundle.js:187279:24)
>     at QueryClientProvider (http://localhost:3000/static/js/bundle.js:227001:21)
>     at ErrorBoundary (http://localhost:3000/static/js/bundle.js:128856:5)
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
> ```
