### ISSUE TITLE
React.forwardRef and @emotion/babel-plugin with Next.js causes hydration error

### ISSUE THREAD

**Issue by WestonThayer** [emotion-js/emotion#2926]
**Current behavior:**

**To reproduce:** https://github.com/WestonThayer/bug-emotion-forwardRef-hydration

A `React.forwardRef` component using the `css` prop results in a console error:

```
Warning: Prop `className` did not match. Server: "css-5nc299-Button" Client: "css-zanegv"
    at button
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at _c
    at div
    at Index
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:94:5)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20742)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23635)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:111:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:296:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:504:25) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

**Expected behavior:**

No hydration error.

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.10.4
- `@emotion/babel-plugin` version: 11.10.2

**Comment by cullylarson** [comment]
I'm seeing the same issue:

```
"@emotion/css": "^11.10.5"
"@emotion/react": "^11.10.5"
"@emotion/server": "^11.10.0"
"@emotion/styled": "^11.10.5"
"react": "^18.2.0"
"@babel/preset-react": "^7.18.6"
```

**Comment by Andarist** [comment]
What are you using on the server side and in which browser do you see the problem being reported?

**Comment by cullylarson** [comment]
@Andarist I updated original reply.

**Comment by cullylarson** [comment]
FYI, here's a similar issue with react-player: https://github.com/cookpete/react-player/issues/1474. I'm not sure if they're related.
