### ISSUE TITLE
"prepend: true" (inside createEmotionCache) not working with emotion and chakra

### ISSUE THREAD

**Issue by aaacafe786** [emotion-js/emotion#2935]
**Current behavior:**

I am having troubles with emotion and chakra inside a remix app,

https://github.com/remix-run/examples/blob/ddae76e84e68ac6f54cab20aff894288e04d104a/chakra-ui/app/root.tsx
i have followed this guide, when i try to use createEmotionCache({ prepend: true, key: 'css' }); i get the the following error: 

```
react-dom.development.js:86 Warning: Expected server HTML to contain a matching <meta> in <head>.
    at meta
    at Meta (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:2848:7)
    at head
    at html
    at Document (http://localhost:3000/build/root-JZQYCU34.js:204:19)
    at App (http://localhost:3000/build/root-JZQYCU34.js:210:27)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:2592:3)
    at Routes2 (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:2575:7)
    at Router (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:679:15)
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:1079:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:1004:5)
    at RemixEntry (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:2472:12)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-W4EP5QPD.js:3230:27)

Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (chunk-4ARRWZOC.js:14522:17)
    at tryToClaimNextHydratableInstance (chunk-4ARRWZOC.js:14543:15)
    at updateHostComponent (chunk-4ARRWZOC.js:19755:13)
    at beginWork (chunk-4ARRWZOC.js:20861:22)
    at HTMLUnknownElement.callCallback2 (chunk-4ARRWZOC.js:8968:22)
    at Object.invokeGuardedCallbackDev (chunk-4ARRWZOC.js:8993:24)
    at invokeGuardedCallback (chunk-4ARRWZOC.js:9027:39)
    at beginWork$1 (chunk-4ARRWZOC.js:24653:15)
    at performUnitOfWork (chunk-4ARRWZOC.js:24086:20)
    at workLoopConcurrent (chunk-4ARRWZOC.js:24077:13)
```
there is are some articles which suggest using insertionPoint instead of prepend, but you get the same error

similar articles which suggest using insertionPoint: 
https://github.com/emotion-js/emotion/issues/2790
https://github.com/emotion-js/emotion/issues/2803

the issue has been ongoing since react 17, here you can find a forum which documents my issue: https://discord.com/channels/660863154703695893/1022835278173450341/1022835278173450341

**To reproduce:**

Please clone the example app in the repo above and try to add the "prepend: true" to the createEmotionCache function, furthermore, please install the loom extension, react 18 fails to hydrate in both instances

**Expected behavior:**

the page should load without any errors

**Environment information:**

```
  "dependencies": {
    "@chakra-ui/react": "^2.3.6",
    "@emotion/react": "^11.10.4",
    "@emotion/server": "^11.10.0",
    "@emotion/styled": "^11.10.4",
    "@remix-run/node": "*",
    "@remix-run/react": "*",
    "@remix-run/serve": "*",
    "framer-motion": "^6.5.1",
    "isbot": "^3.5.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "*",
    "@remix-run/eslint-config": "*",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.13",
    "eslint": "^8.10.0",
    "typescript": "^4.7.4"
  },
```

**Comment by aaacafe786** [comment]
i have tried including the fix: 
```
document.querySelectorAll('loom-container').forEach((s) => {
    s.parentNode.removeChild(s);
});
``` 

it does not seem to make a difference
