### ISSUE TITLE
@emotion/babel-plugin >= 11.11.0 errors

### ISSUE THREAD

**Issue by Nantris** [emotion-js/emotion#3254]
**Current behavior:**

```
ERROR in ./app/main.dev.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Unexpected falsy value: undefined
    at createDescriptor (/home/me/Documents/projects/myproject/node_modules/@babel/core/src/config/config-descriptors.ts:335:11)
    at createDescriptor.next (<anonymous>)
    at step (/home/me/Documents/projects/myproject/node_modules/gensync/index.js:261:32)
    at /home/me/Documents/projects/myproject/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/me/Documents/projects/myproject/node_modules/gensync/index.js:223:11)
```

**To reproduce:**

Upgrade from plugin 11.10.x to 11.11 or 11.12

**Expected behavior:**

No errors, identical to previous babel plugin versions.

I tried `yarn upgrade` also, but the issue persists.

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.13.3

**Comment by Nantris** [comment]
Friendly bump. Is there any problem staying on the old version? I've seen this issue for many months but only just got around to reporting it.

**Comment by Nantris** [comment]
I see I duplicated #3192.
