### ISSUE TITLE
emotion theming Typescript typing issue

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#456]
- `emotion` version: 8.0.10
- `react` version:

Relevant code.

```javascript

```

What you did:

What happened:
```bash
Error: /home/travis/build/emotion-js/emotion/packages/emotion-theming/types/tests.tsx
ERROR: 27:74  expect  TypeScript@next compile error: 
Type 'typeof "/home/travis/build/emotion-js/emotion/packages/emotion-theming/types/index"' cannot be converted to type 'EmotionThemingModule<{ primary: string; secondary: string; }>'.
  Types of property 'ThemeProvider' are incompatible.
    Type 'ComponentClass<ThemeProviderProps<object>>' is not comparable to type 'ComponentClass<ThemeProviderProps<{ primary: string; secondary: string; }>>'.
      Type 'Component<ThemeProviderProps<object>, ComponentState>' is not comparable to type 'Component<ThemeProviderProps<{ primary: string; secondary: string; }>, ComponentState>'.
        Type 'ThemeProviderProps<object>' is not comparable to type 'ThemeProviderProps<{ primary: string; secondary: string; }>'.
    at /home/travis/build/emotion-js/emotion/node_modules/dtslint/bin/index.js:76:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/emotion-js/emotion/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
```

Reproduction:
https://travis-ci.org/emotion-js/emotion/builds/299876126?utm_source=github_status&utm_medium=notification

Problem description:
This _seems_ to go away if you clear the cache on travis, but I want to see if we can figure out whats going on.

cc
@cameron-martin 
@asvetliakov
@renatorib

**Comment by cameron-martin** [comment]
This is weird. I'm wondering if `typescript@next` at that time (which would have been either `2.7.0-dev.20171108` or `2.7.0-dev.20171109`) was just buggy.
