### ISSUE TITLE
Cannot use react-emotion without emotion-theming

### ISSUE THREAD

**Issue by CraigCav** [emotion-js/emotion#467]
- `emotion` version: 8.0.10
- `react` version: 16.0.0

### Problem description:
When seeing up a new project using react-emotion (without also setting up emotion-theming with a `ThemeProvider`, I get the following error in my console:

```term
TypeError: Cannot read property 'theme' of undefined
    at Styled.render (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-emotion/dist/index.cjs.js:159:42)
```

### What you did:
I can avoid the error by including a theme provider, but this seems unnecessary as I'm not using themes.

```javascript

  <ThemeProvider theme={{}}>
    <app />
  </ThemeProvider>

```

### Suggested solution:
It seems like it should be possible to use react-emotion without emotion-theming. I __think__ if the following null check is update to check for `undefined`,  the error is avoided: https://github.com/emotion-js/emotion/blob/6992084aa91c824cc723db0e66dbb50a0b59f443/packages/react-emotion/src/index.js#L88

**Comment by probablyup** [comment]
Your solution makes sense to me.

**Comment by mitchellhamilton** [comment]
@CraigCav Could you share the full stack trace? React initialisises state to null so this shouldn't happen.

**Comment by CraigCav** [comment]
@mitchellhamilton I was under the impression that React doesn't set state to null for ES6 classes, but I definitely could be wrong about that. A quick Google search indicates that undefined state is expected if state isn't set in the constructor: http://willi.am/blog/2015/05/07/react-this-dot-state-is-undefined/ 

I can throw a reproduction into a repository if that helps? It's pretty easy to reproduce, just use the react-emotion styled.div`` syntax in any app that doesn't include a `ThemeProvider`.

**Comment by mitchellhamilton** [comment]
@CraigCav [React does indeed initialise state to null. `styled` also works fine without a `ThemeProvider`](https://codesandbox.io/s/9y1xzx90jo). [We also use it without a `ThemeProvider` in tests a lot](https://github.com/emotion-js/emotion/blob/master/packages/react-emotion/test/index.test.js#L14). 

A reproduction would be helpful.

**Comment by CraigCav** [comment]
@mitchellhamilton thanks for looking into this - it definitely looks like there's more to my error than I had first thought. I'll put together a reproduction!

**Comment by CraigCav** [comment]
Here's the full stack trace i'm seeing:

```term
TypeError: Cannot read property 'theme' of undefined
    at Styled.render (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-emotion/dist/index.cjs.js:151:43)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:697:32)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at /Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:722:21
    at forEachSingleChild (/Users/craigcavalier/workspace/ezcater/store/node_modules/react/cjs/react.development.js:883:8)
    at traverseAllChildrenImpl (/Users/craigcavalier/workspace/ezcater/store/node_modules/react/cjs/react.development.js:787:5)
    at traverseAllChildrenImpl (/Users/craigcavalier/workspace/ezcater/store/node_modules/react/cjs/react.development.js:803:23)
    at traverseAllChildren (/Users/craigcavalier/workspace/ezcater/store/node_modules/react/cjs/react.development.js:858:10)
    at Object.forEachChildren [as forEach] (/Users/craigcavalier/workspace/ezcater/store/node_modules/react/cjs/react.development.js:903:3)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:720:28)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at walkTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:711:17)
    at getQueriesFromTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:732:5)
    at getDataFromTree (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:747:19)
    at renderToStringWithData (/Users/craigcavalier/workspace/ezcater/store/node_modules/react-apollo/react-apollo.umd.js:769:12)
    at Object._callee$ (/Users/craigcavalier/workspace/ezcater/store/build/server.js:2805:96)
    at tryCatch (/Users/craigcavalier/workspace/ezcater/store/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/craigcavalier/workspace/ezcater/store/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/craigcavalier/workspace/ezcater/store/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/craigcavalier/workspace/ezcater/store/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/craigcavalier/workspace/ezcater/store/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/Users/craigcavalier/workspace/ezcater/store/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/craigcavalier/workspace/ezcater/store/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at /Users/craigcavalier/workspace/ezcater/store/build/server.js:2837:18
    at Layer.handle [as handle_request] (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/layer.js:95:5)
    at /Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/index.js:281:22
    at param (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/craigcavalier/workspace/ezcater/store/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/craigcavalier/workspace/ezcater/store/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/Users/craigcavalier/workspace/ezcater/store/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/craigcavalier/workspace/ezcater/store/node_modules/send/index.js:421:12)
    at next (/Users/craigcavalier/workspace/ezcater/store/node_modules/send/index.js:736:16)
    at onstat (/Users/craigcavalier/workspace/ezcater/store/node_modules/send/index.js:725:14)
    at FSReqWrap.oncomplete (fs.js:152:21)
```

Based on the stack trace, I suspect it must be related to either server rendering, or use within react-apollo. I'll keep working to isolate and put together a reproduction.

**Comment by tkh44** [comment]
Looking around, it looks like react-apollo messes with the instances as it walks the tree for SSR. I wonder if this could have anything to do with it.

https://github.com/apollographql/react-apollo/blob/b52b017e525586be6acfe4895b71411aabc77b8d/src/getDataFromTree.ts#L51-L85

**Comment by mitchellhamilton** [comment]
@CraigCav Could you update react-apollo? This issue was recently fixed in react-apollo.

**Comment by CraigCav** [comment]
@tkh44 @mitchellhamilton Thanks to both of you for digging into this. You're absolutely right, `react-apollo` was messing with the instances and causing the state to be set to `undefined` instead of `null`. 

Updating from `react-apollo` from `2.0.0` to `2.0.1` resolves this issue.

Thanks again for your help!
