### ISSUE TITLE
Jest failing on snapshots with jest-emotion

### ISSUE THREAD

**Issue by krisbulman** [emotion-js/emotion#538]
- `emotion` version: 8.0.12
- `react` version: 15.5.4
- `jest` version:  21.2.1
- `jest-emotion` version:  9.0.0-0
- `enzyme` version:  3.2.0

**Button.js**
```javascript
import React from 'react';
import { css } from 'react-emotion';

const baseButtonStyle = css`
  background-color: blue;
`;

const Button = props => (
  <button
    className={baseButtonStyle(props)}
    disabled={props.disabled}
  >
    <span>{props.text}</span>
  </button>
);

export default Button;
```

**Button.test.js**
```javascript
import React from 'react';
import { mount } from 'enzyme';
import toJson from 'enzyme-to-json';
import { createSerializer } from 'jest-emotion';
import * as emotion from 'emotion';

import Button from './Button';

expect.addSnapshotSerializer(createSerializer(emotion));

describe('Button', () => {
  const defaultProps = {
    text: 'Submit',
    type: 'button',
  };

  it('renders initially', () => {
    const wrapper = mount(<Button {...defaultProps} />);

    expect(toJson(wrapper)).toMatchSnapshot();
  });
});
```

What you did:
`yarn run jest components/Button/Button.test.js`

What happened:
```
 FAIL  components/Button/Button.test.js
  TypeError: Cannot read property 'inserted' of undefined

  at Object.<anonymous> (components/Button/Button.test.js:20:50)
  at process._tickCallback (internal/process/next_tick.js:109:7)
```

Problem description:
Snapshots will not generate, instead, I get this error. Before adding `jest-emotion` as per docs, they generated without error but I ran into the auto generated class names. Any idea how to get around this?

**Comment by mitchellhamilton** [comment]
Those docs are for Emotion 9, as mentioned in the README. For testing with emotion 8, use jest-glamor-react. https://github.com/emotion-js/emotion/blob/v8.0.12/docs/testing.md

**Comment by krisbulman** [comment]
👍
