### ISSUE TITLE
jest-emotion cannot parse @supports CSS rule

### ISSUE THREAD

**Issue by jerelmiller** [emotion-js/emotion#604]
- `emotion` version: 9.0.2
- `react` version: 16.2.0
- `jest-emotion` version: 9.0.0

Relevant code.

```javascript
const Left = styled.div`
  display: flex;
  align-items: center;

  @supports (display: grid) {
    display: grid;
  }
`
```

What you did:

I have a few snapshot tests for components like the above that use the `@supports` CSS rule. The error shows up when trying to snapshot test a component like the above.

What happened:

```
console.error node_modules/jest-emotion/lib/index.js:92
    { Error: undefined:1:80430: @supports missing '}'
        at error (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:62:15)
        at atsupports (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:336:26)
        at atrule (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:536:10)
        at rules (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:117:58)
        at atsupports (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:334:35)
        at atrule (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:536:10)
        at rules (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:117:58)
        at stylesheet (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:81:21)
        at Object.<anonymous>.module.exports [as parse] (/Users/me/code/my-project/node_modules/css/lib/parse/index.js:564:20)
        at getStylesFromSelectors (/Users/me/code/my-project/node_modules/jest-emotion/lib/index.js:90:17)
        at Object.print (/Users/me/code/my-project/node_modules/jest-emotion/lib/index.js:75:18)
        at printPlugin (/Users/me/code/my-project/node_modules/pretty-format/build/index.js:266:12)
        at printer (/Users/me/code/my-project/node_modules/pretty-format/build/index.js:318:12)
        at printComplexValue (/Users/me/code/my-project/node_modules/pretty-format/build/index.js:193:12)
        at prettyFormat (/Users/me/code/my-project/node_modules/pretty-format/build/index.js:483:10)
        at Object.<anonymous>.exports.serialize.data (/Users/me/code/my-project/node_modules/jest-snapshot/build/utils.js:137:30)
        at SnapshotState.match (/Users/me/code/my-project/node_modules/jest-snapshot/build/State.js:121:53)
        at Object.toMatchSnapshot (/Users/me/code/my-project/node_modules/jest-snapshot/build/index.js:64:32)
        at Object.throwingMatcher [as toMatchSnapshot] (/Users/me/code/my-project/node_modules/expect/build/index.js:214:24)
        at Object.test (/Users/me/code/my-project/node_modules/@storybook/addon-storyshots/dist/test-bodies.js:51:20)
        at Object.<anonymous> (/Users/me/code/my-project/node_modules/@storybook/addon-storyshots/dist/index.js:174:28)
        at Object.asyncFn (/Users/me/code/my-project/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
        at resolve (/Users/me/code/my-project/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
        at new Promise (<anonymous>)
        at mapper (/Users/me/code/my-project/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
        at promise.then (/Users/me/code/my-project/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
        at <anonymous>
```

Reproduction:

Run a snapshot test with a component that uses `@supports`

Problem description:

Suggested solution:

**Comment by mitchellhamilton** [comment]
@jerelmiller Could you try updating to 9.1.0 and seeing if this still happens?

**Comment by jerelmiller** [comment]
Hey @mitchellhamilton. It does indeed look like it has been fixed! I now have passing tests. Thanks for fixing this!

I did happen to notice one side effect. Its not a deal-breaker, but just a tad annoying. It looks like now there is a console error that is displayed. It looks like this:

```
 console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Could not parse CSS stylesheet
        at exports.createStylesheet (/Users/me/code/my-project/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
        at HTMLStyleElementImpl._updateAStyleBlock (/Users/me/code/my-project/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
        at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/me/code/my-project/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:37:12)
        at HTMLStyleElementImpl.insertBefore (/Users/me/code/my-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:225:14)
        at HTMLStyleElementImpl.appendChild (/Users/me/code/my-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:327:17)
        at HTMLStyleElement.appendChild (/Users/me/code/my-project/node_modules/jsdom/lib/jsdom/living/generated/Node.js:192:45)
        at _StyleSheet._insert [as insert] (/Users/me/code/my-project/node_modules/create-emotion/dist/index.cjs.js:174:10)
        at insertRule (/Users/me/code/my-project/node_modules/create-emotion/dist/index.cjs.js:228:13)                                                                              at toSheet (/Users/me/code/my-project/node_modules/stylis-rule-sheet/index.js:16:6)                                                                                         at Array.forEach (<anonymous>) @supports (display:grid){.css-171bbl8{display:grid;justify-items:center;-webkit-box-pack:unset;-webkit-justify-content:unset;-ms-flex-pack:
unset;justify-content:unset;-webkit-align-items:unset;-webkit-box-align:unset;-ms-flex-align:unset;align-items:unset;grid-auto-flow:row;grid-gap:1.25rem;}}
```

Thanks again for fixing!

**Comment by mitchellhamilton** [comment]
@jerelmiller I had a quick look and it seems the css parser jsdom uses doesn't support `@supports` yet and [there's a PR for it but it doesn't have tests](https://github.com/NV/CSSOM/pull/94) so it hasn't been merged yet.

**Comment by jerelmiller** [comment]
Fantastic. I'll keep an eye on that PR. Good to know its something on the jest/jsdom end. Here's to hoping we can see that merged soon! Thanks for checking into that!
