### ISSUE TITLE
Jest-emotion with create-emotion & create-emotion-styled

### ISSUE THREAD

**Issue by nmackey** [emotion-js/emotion#627]
- `emotion` version: 9.1.1
- `react` version: 16.2.1

Relevant code.

```javascript

```

What you did:
Tried to do snapshot testing with `jest-emotion` and my app which is using `create-emotion` & `create-emotion-styled`

What happened:
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)

      26 |     const textComponents = renderer.create(<NavTitle>NavigationTitle</NavTitle>);
      27 |     console.log(textComponents.toJSON());
    > 28 |     expect(textComponents).toMatchSnapshot();
      29 |   });
      30 | });
      31 |

      at getStyles (../../node_modules/jest-emotion/lib/index.js:55:17)
      at getStylesFromSelectors (../../node_modules/jest-emotion/lib/index.js:87:18)
      at Object.print (../../node_modules/jest-emotion/lib/index.js:75:18)
      at printPlugin (../../node_modules/pretty-format/build/index.js:270:12)
      at printer (../../node_modules/pretty-format/build/index.js:322:12)
      at printComplexValue (../../node_modules/pretty-format/build/index.js:197:12)
      at prettyFormat (../../node_modules/pretty-format/build/index.js:487:10)
      at Object.throwingMatcher (../../node_modules/expect/build/index.js:215:24)
      at Object.<anonymous> (src/components/__tests__/Text.test.jsx:28:28)

Reproduction:
Run a regular snapshot test using a custom instance of emotion created by `create-emotion`

Problem description:
When trying to use `jest-emotion` with my own instance of `emotion` it doesn't seem to work.  If I use the regular versions of `emotion` and `react-emotion` the tests work fine.  (however I need to create my own instance to control style insertion ordering)

Suggested solution:
`emotion.caches.inserted` seems to be undefined on line 55 of `index.js` in `jest-emotion`

**Comment by mitchellhamilton** [comment]
[We have tests that do this and they are working](https://github.com/emotion-js/emotion/tree/master/packages/create-emotion/test), could you create a reproduction in a GitHub repo?

**Comment by nmackey** [comment]
I'll check those tests out and I'll try to reproduce in another repo.  Thanks

**Comment by nmackey** [comment]
Yep, this was a mistake in my test setup.  My instance of `emotion` was not the one I thought it was.  Thanks for your help quick reply.
