### ISSUE TITLE
babel-plugin-emotion - cannot find module

### ISSUE THREAD

**Issue by dprokop** [emotion-js/emotion#913]
- `emotion` version: 8.0.12
- `react` version: 16.5.2
- `babel` version: 7.1.2
- `node` version 8.12.0
- `npm` version 6.4.1

What happened:

Recently I have started encountering such bug in my build pipeline. Problem seems to be node/npm version agnostic. 

```
{ Error: Cannot find module 'babel-plugin-emotion' from '/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web'
- If you want to resolve "emotion", use "module:emotion"
    at Function.module.exports [as sync] (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/resolve/lib/sync.js:42:15)
    at resolveStandardizedName (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/tmp/build_a4ddf0b56b0ca3a3c4f8a3b7cf351db6/web/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
```

My `.babelrc`:
```
{
  "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]],
  "env": {
    "production": {
      "plugins": [["emotion", { "sourceMap": false, "hoist": true }]]
    },
    "development": {
      "plugins": [["emotion", { "sourceMap": true, "hoist": false }]]
    }
  },

  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

Have you guys ever noticed problem like that?

**Comment by Ailrun** [comment]
Thank you for your report!
Could you provide minimal reproduction too?

**Comment by dprokop** [comment]
@Ailrun Yeah, here comes the problem. I cannot reproduce it anywhere but on Heroku. Me and my team tried to reproduce it on multiple environments, and the problem seems to be non existent. I have some gut feeling this might be Heroku's issue, but then I can see no reasoning to support that.

**Comment by Ailrun** [comment]
So it does not work only with Heroku?
Hm... That's weird

**Comment by dprokop** [comment]
@Ailrun please see this repository https://github.com/dprokop/babel-emotion-repro for a repoduction scenario

**Comment by dprokop** [comment]
Ah, sorry. `build`

**Comment by tkh44** [comment]
Could you try running with emotion 9, even if just as a sample case? I'm not sure emotion 8 works with babel 7. It's been a while so I'm not 100% 😅

**Comment by dprokop** [comment]
@tkh44 @Ailrun bumping to version 9 fixes the issue. Thanks! 

Still, I completely cannot understand why it's Heroku that has a problem with emotion 8. It works everywhere but not on Heroku. Very, very strange.

**Comment by tkh44** [comment]
I'm glad you got it figured out. Gonna close this for now.
